version: '3.3'
services:
  calenderback:
    build: ./calenderback
    ports:
      - "8085:8085"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=calender
      - DB_USER=postgres
      - DB_PASSWORD=postgres
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calender
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - "8082:8080"